"""Evaluation harness: measure the detectors against known ground truth.

The harness joins detector output to attack ground truth *after* the analysis
has run.  A detector never sees ground truth; the pipeline is invoked exactly as
it would be on an unknown dataset.

Reported metrics and what they mean
-----------------------------------
``precision`` / ``recall`` / ``f1``
    Per attack class, over sample-level predictions.  Positives are the samples
    the scenario's ground truth marks as affected by *that* class.

``fpr_clean``
    False positives measured over samples that the scenario did not touch at
    all.  This is the headline false-alarm number, because it answers "how often
    does this detector accuse an innocent sample".

``fpr_all_negatives``
    The same, but counting samples affected by a *different* attack class as
    negatives too.  Always reported alongside ``fpr_clean`` and always higher:
    an out-of-distribution insertion genuinely can have an odd label
    neighbourhood, and hiding that behind the friendlier number would be a
    quiet overstatement.

``auroc``
    Threshold-free ranking quality, computed where the detector produced a score
    for every analysed sample. Absent where it does not (deterministic
    detectors have no ranking to assess).

Every metric is reported with its evaluation population and the scenario,
seed and sample counts that produced it.  A metric without those is not a
measurement, it is a claim.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable, Sequence

from pydantic import BaseModel, ConfigDict, Field

from ..core.config import Config
from ..core.evidence import utc_now_iso
from ..core.logging import get_logger
from ..pipeline import analyse
from ..risk.calibration import CalibrationSet, DetectorCalibration, build_table

log = get_logger("attack_lab.evaluate")

EVALUATION_SCHEMA_VERSION = "1.0"


class ClassMetrics(BaseModel):
    model_config = ConfigDict(extra="forbid")

    attack_class: str
    detector: str | None
    population: dict[str, int]
    true_positives: int
    false_positives: int
    false_negatives: int
    precision: float
    recall: float
    f1: float
    fpr_clean: float
    fpr_all_negatives: float
    auroc: float | None = None
    coverage: str | None = None
    missed_examples: list[str] = Field(default_factory=list)
    false_positive_examples: list[str] = Field(default_factory=list)
    tolerated_overlap: int = Field(
        default=0,
        description="Predictions excused because the sample was affected by a "
        "related attack class (see TOLERATED_OVERLAP).",
    )
    predicted_actionable: int = Field(
        default=0,
        description="Predictions the analyst would actually act on: findings of "
        "severity MEDIUM or above. Findings the pipeline itself downgraded -- "
        "for example a label finding on a sample that is also out-of-distribution "
        "-- are excluded.",
    )
    precision_actionable: float | None = Field(
        default=None,
        description="Precision restricted to actionable findings. Reported "
        "alongside raw precision because the two answer different questions: "
        "'how often is the detector right' versus 'how often is the analyst "
        "sent somewhere useful'. None when the detector produced no actionable "
        "sample-level findings -- including classes such as systematic_mislabel "
        "whose findings are contributor-level by design, where the metric does "
        "not apply rather than being zero.",
    )
    recall_actionable: float = 0.0


class ScenarioResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    scenario: str
    seed: int
    dataset_digest: str
    report_id: str
    total_samples: int
    affected_samples: int
    duration_ms: int
    throughput_samples_per_s: float
    metrics: list[ClassMetrics]
    overall_assessment: str
    findings_total: int


class EvaluationReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: str = EVALUATION_SCHEMA_VERSION
    generated_at: str = Field(default_factory=utc_now_iso)
    config_hash: str
    software_version: str
    scenarios: list[ScenarioResult]
    evaluation_population: str = (
        "Synthetic attack-lab corpus generated by cvtrust.attack_lab.synth. "
        "Metrics describe detector behaviour on this corpus under the stated "
        "seeds and parameters. They are a lower bound on evidence quality, not "
        "a prediction of operational performance on real imagery."
    )


#: Attack classes whose samples a given detector may legitimately flag without
#: it counting as a false positive.
#:
#: A systematically mislabelled sample *is* a mislabelled sample, so the
#: label-consistency detector flagging it is correct behaviour, not an error --
#: scoring it as a false positive for ``label_flip`` would penalise the detector
#: for being right.  Likewise an exact duplicate is also a near duplicate.
#: Recall is still measured against the exact class only; this map affects the
#: false-positive count alone, and every metric reports which samples it
#: excused.
TOLERATED_OVERLAP: dict[str, frozenset[str]] = {
    "label_flip": frozenset({"systematic_mislabel"}),
    "systematic_mislabel": frozenset(),
    "near_duplicate_flood": frozenset({"duplicate_flood"}),
    "duplicate_flood": frozenset(),
    "ood_insertion": frozenset(),
    "metadata_inconsistency": frozenset(),
}


def _confusion(
    predicted: set[str],
    positives: set[str],
    clean: set[str],
    all_samples: set[str],
    tolerated: set[str] | None = None,
) -> dict[str, Any]:
    tolerated = tolerated or set()
    true_positives = predicted & positives
    false_positives = predicted - positives - tolerated
    false_negatives = positives - predicted
    negatives_all = all_samples - positives - tolerated
    false_positives_clean = false_positives & clean

    precision = len(true_positives) / len(predicted) if predicted else 0.0
    recall = len(true_positives) / len(positives) if positives else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )
    return {
        "true_positives": len(true_positives),
        "false_positives": len(false_positives),
        "false_negatives": len(false_negatives),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "fpr_clean": len(false_positives_clean) / len(clean) if clean else 0.0,
        "fpr_all_negatives": (
            len(false_positives) / len(negatives_all) if negatives_all else 0.0
        ),
        "missed_examples": sorted(false_negatives)[:10],
        "false_positive_examples": sorted(false_positives)[:10],
        "tolerated_overlap": len(predicted & tolerated),
    }


def _auroc(scores: dict[str, float], positives: set[str], population: Iterable[str]) -> float | None:
    population = [s for s in population if s in scores]
    labels = [1 if s in positives else 0 for s in population]
    if len(set(labels)) < 2 or len(population) < 4:
        return None
    try:
        from sklearn.metrics import roc_auc_score
    except ImportError:  # pragma: no cover - scikit-learn is a core dependency
        return None
    return float(roc_auc_score(labels, [scores[s] for s in population]))


def evaluate_scenario(
    scenario_dir: Path, config: Config, *, reference_from_clean: bool = True
) -> tuple[ScenarioResult, dict[str, dict[str, Any]]]:
    """Run the pipeline over one attacked scenario and score it.

    ``reference_from_clean`` declares the scenario's untouched samples as the
    OOD reference distribution.  That models the realistic deployment: an
    analyst has a trusted baseline and is assessing a new submission against it.
    Without a declared reference the OOD detector falls back to self-reference
    and says so, which is a materially weaker claim.
    """
    scenario_dir = Path(scenario_dir)
    ground_truth = json.loads(
        (scenario_dir / "ground_truth.json").read_text(encoding="utf-8")
    )
    root = scenario_dir / "dataset"
    clean = set(ground_truth.get("clean", []))

    report, _, outputs = analyse(
        root, config, reference_sample_ids=clean if reference_from_clean else None
    )

    all_samples = {record.sample_id for record in report_samples(report, root)}
    affected: dict[str, dict[str, Any]] = ground_truth.get("affected", {})

    from ..core.evidence import SEVERITY_ORDER, AssetType, Severity

    actionable_by_class: dict[str, set[str]] = {}
    for finding in report.findings:
        if finding.asset.type is not AssetType.SAMPLE:
            continue
        if SEVERITY_ORDER[finding.severity] < SEVERITY_ORDER[Severity.MEDIUM]:
            continue
        actionable_by_class.setdefault(finding.attack_class, set()).add(finding.asset.id)

    by_class: dict[str, set[str]] = {}
    for relpath, detail in affected.items():
        by_class.setdefault(detail.get("attack_class", "unknown"), set()).add(relpath)

    coverage_by_class = {e.attack_class: e.coverage.value for e in report.coverage.entries}
    predicted_by_class: dict[str, set[str]] = {}
    scores_by_class: dict[str, dict[str, float]] = {}
    detector_by_class: dict[str, str] = {}
    for output in outputs:
        for attack_class, flagged in output.flagged.items():
            predicted_by_class.setdefault(attack_class, set()).update(flagged)
            detector_by_class.setdefault(attack_class, output.detector)
        for attack_class, scores in output.scores.items():
            scores_by_class.setdefault(attack_class, {}).update(scores)

    metrics: list[ClassMetrics] = []
    calibration_inputs: dict[str, dict[str, Any]] = {}

    for attack_class in sorted(set(by_class) | set(predicted_by_class)):
        positives = by_class.get(attack_class, set())
        predicted = predicted_by_class.get(attack_class, set())
        tolerated = {
            relpath
            for other in TOLERATED_OVERLAP.get(attack_class, frozenset())
            for relpath in by_class.get(other, set())
        }
        confusion = _confusion(predicted, positives, clean, all_samples, tolerated)
        actionable = actionable_by_class.get(attack_class, set())
        actionable_tp = actionable & positives
        actionable_scored = actionable - tolerated
        confusion["predicted_actionable"] = len(actionable)
        confusion["precision_actionable"] = (
            len(actionable_tp) / len(actionable_scored) if actionable_scored else None
        )
        confusion["recall_actionable"] = (
            len(actionable_tp) / len(positives) if positives else 0.0
        )
        scores = scores_by_class.get(attack_class, {})
        metrics.append(
            ClassMetrics(
                attack_class=attack_class,
                detector=detector_by_class.get(attack_class),
                population={
                    "total_samples": len(all_samples),
                    "positives": len(positives),
                    "clean_negatives": len(clean),
                    "all_negatives": len(all_samples - positives),
                    "predicted": len(predicted),
                },
                coverage=coverage_by_class.get(attack_class),
                auroc=_auroc(scores, positives, all_samples),
                **confusion,
            )
        )
        if predicted and scores:
            calibration_inputs[attack_class] = {
                "detector": detector_by_class.get(attack_class),
                "scores": [scores.get(s, 1.0) for s in sorted(predicted)],
                "labels": [s in positives or s in tolerated for s in sorted(predicted)],
                "scenario": ground_truth.get("scenario"),
                "seed": ground_truth.get("seed"),
                "n_samples": len(all_samples),
            }

    result = ScenarioResult(
        scenario=str(ground_truth.get("scenario", scenario_dir.name)),
        seed=int(ground_truth.get("seed", 0)),
        dataset_digest=report.dataset["digest"],
        report_id=report.report_id,
        total_samples=len(all_samples),
        affected_samples=len(affected),
        duration_ms=report.run.duration_ms or 0,
        throughput_samples_per_s=float(report.dataset["throughput_samples_per_s"]),
        metrics=metrics,
        overall_assessment=report.summary.overall,
        findings_total=report.summary.findings_total,
    )
    return result, calibration_inputs


def report_samples(report, root: Path):
    """Sample records from a report's manifest-derived dataset section."""
    from ..datasets.base import IMAGE_EXTENSIONS

    class _Rec:
        def __init__(self, sample_id: str) -> None:
            self.sample_id = sample_id

    return [
        _Rec(p.relative_to(root).as_posix())
        for p in sorted(root.rglob("*"))
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    ]


def evaluate_all(
    lab_dir: Path,
    config: Config,
    scenarios: Sequence[str] | None = None,
) -> tuple[EvaluationReport, CalibrationSet]:
    lab_dir = Path(lab_dir)
    candidates = sorted(
        d for d in lab_dir.iterdir()
        if d.is_dir() and (d / "ground_truth.json").is_file()
    )
    if scenarios:
        candidates = [d for d in candidates if d.name in set(scenarios)]

    results: list[ScenarioResult] = []
    pooled: dict[str, dict[str, Any]] = {}

    for scenario_dir in candidates:
        log.info("evaluating scenario %s", scenario_dir.name)
        result, calibration_inputs = evaluate_scenario(scenario_dir, config)
        results.append(result)
        for attack_class, payload in calibration_inputs.items():
            entry = pooled.setdefault(
                attack_class,
                {"detector": payload["detector"], "scores": [], "labels": [],
                 "scenarios": [], "n_samples": 0},
            )
            entry["scores"].extend(payload["scores"])
            entry["labels"].extend(payload["labels"])
            entry["scenarios"].append(
                {"scenario": payload["scenario"], "seed": payload["seed"],
                 "n_samples": payload["n_samples"]}
            )
            entry["n_samples"] += payload["n_samples"]

    from ..detectors import DETECTORS

    tables: list[DetectorCalibration] = []
    for attack_class, entry in sorted(pooled.items()):
        detector_name = entry["detector"]
        if detector_name is None:
            continue
        detector = DETECTORS.get(detector_name)
        tables.append(
            build_table(
                detector=detector_name,
                detector_version=detector.version,
                attack_class=attack_class,
                scores=entry["scores"],
                is_true_positive=entry["labels"],
                provenance={
                    "source": "cvtrust attack lab (synthetic)",
                    "scenarios": entry["scenarios"],
                    "flagged_observations": len(entry["scores"]),
                    "generated_at": utc_now_iso(),
                    "caveat": "precision measured on synthetic scenarios; a lower "
                              "bound on evidence quality, not an operational guarantee",
                },
            )
        )

    return (
        EvaluationReport(
            config_hash=config.config_hash(),
            software_version=__import__("cvtrust").__version__,
            scenarios=results,
        ),
        CalibrationSet(created_at=utc_now_iso(), tables=tuple(tables)),
    )
